### ISSUE TITLE
Immersive Portals is incompatible

### ISSUE THREAD

**Issue by SemmieDev** [Mirsario/Minecraft-CameraOverhaul#1]
I am not sure if you will fix this, but I just want to say that immersive portals (https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod) is incompatible. When you load up the mod with this mod it looks like this mod is just disabled and no visible changes will get made.

**Comment by qouteall** [comment]
IP overrides the transformation for two things: 1. Change the camera transformation for portal rendering 2. Display the rotation animation after the player cross a portal with rotation transformation that make the immediate camera pose an illegal camera rotation.
I can disable that transformation override when not rendering portal and no rotation animation is being performed

**Comment by qouteall** [comment]
I noticed that this mod provides an event for changing camera but I prefer quaternion over Euler angle

**Comment by qouteall** [comment]
Maybe fixed in the next version of IP

**Comment by Mirsario** [comment]
0.52 of IP came out, and I can say that the mods are definitely no longer *incompatible*, although it's still not perfect:

https://user-images.githubusercontent.com/6795251/102690876-851fc700-4219-11eb-8557-157eb41dd72c.mp4

@qouteall
Can you not just re-use the main render's view & projection matrices, and only override location of the former one and offset rotation? Regardless, thanks a lot.

**Comment by nodogsleft** [comment]
I wrote you a reply on the curseforge page, but fixing this caused an issue when using both mods: the camera shakes rapidly in backwards third-person mode. This did not occur prior to the Immersive Portals fix.

**Comment by Mhowser** [comment]
> I wrote you a reply on the curseforge page, but fixing this caused an issue when using both mods: the camera shakes rapidly in backwards third-person mode. This did not occur prior to the Immersive Portals fix.

I was about to report this as well.
